#include "Dshot600.h"

#include "hardware/pio.h"
#include "hardware/clocks.h"

// This header is automatically generated by CMake from dshot.pio
#include "Dshot600.pio.h"

// We assume PIO0 for this library to keep it simple
#define DSHOT_PIO pio0

void dshot_init(uint pin, uint sm)
{
    // Load the program into PIO memory.
    // We only need to load it once, even if using multiple state machines.
    static uint offset = 0;
    static bool program_loaded = false;

    if (!program_loaded)
    {
        offset = pio_add_program(DSHOT_PIO, &dshot_program);
        program_loaded = true;
    }

    // Initialize the specific state machine and pin
    dshot_program_init(DSHOT_PIO, sm, offset, pin);
}

void dshot_send_frame(uint sm, uint16_t frame)
{
    // Push the frame to the TX FIFO.
    // Shift left by 16 because the PIO shifts out from the MSB.
    pio_sm_put_blocking(DSHOT_PIO, sm, (uint32_t)frame << 16);
}